### ISSUE TITLE
create frontend component

### ISSUE THREAD

**Issue by Ashmit-Verma** [swciitg/Sports_Board_Portal#1]
![image](https://github.com/user-attachments/assets/0b4a2e87-f83d-49c4-b038-8ef860a82e0f)
![image](https://github.com/user-attachments/assets/26edf73a-97a1-4676-a05f-4b9083d035c6)

Create responsive header and footer using react and tailwind

**Comment by Ash-D3v** [comment]
hey @Ashmit-Verma  i would like to do this please assign it to me under the labels

**Comment by madmaxWMFU** [comment]
Hi! Can you assign it to me?

**Comment by Ashmit-Verma** [comment]
Please check out other repos like intranetSearch
