### ISSUE TITLE
Create frontend component 4

### ISSUE THREAD

**Issue by Ashmit-Verma** [swciitg/Sports_Board_Portal#9]
![image](https://github.com/user-attachments/assets/9ccc42bb-c625-4e0f-bb00-2af145461bca)
Create past events and achievements section for the club page .
Make responsive ui using react and tailwind . Try to stick to the design

**Comment by Vibha17** [comment]
@Ashmit-Verma Assign this to me.

**Comment by Ashmit-Verma** [comment]
> @Ashmit-Verma Assign this to me.

assigned to you @Vibha17
